### ISSUE TITLE
Is there is any feature of cutting the mesh by giving exact size of cut for boundary cutting using mesh-cutter library?

### ISSUE THREAD

**Issue by ghost** [hugoscurti/mesh-cutter#6]
Respected All,
I have a set of 3D data mesh file which look uniform plane. I want to cut the boundary of this mesh by 0.09 cm using coding. I was researching and found the mesh cutter library. I am very excited to work with this library. I tried the same using Meshlab software. But, I am unable to do cut the boundary mesh using a mesh cutter. I need mesh cutting for the boundary of 0.09 since I want to work on further processes using simulation, based on this mesh.

Any leads will be appreciated.
Thanks in advance

**Comment by hugoscurti** [comment]
Hi. I'm not sure this project would help you in doing so. What this project does is really just split a mesh in 2 at runtime by cutting the edges that intersect with a certain plane. It doesn't cut by a size or anything, nor does it go through all boundaries of an object. 

I'm guessing you would need to iterate over the object's nodes and move the nodes along the intersecting edge in the opposite normal direction? (i.e. to reduce the boundary for 0.09 cm)

Hope this helps

**Comment by ghost** [comment]
> Hi. I'm not sure this project would help you in doing so. What this project does is really just split a mesh in 2 at runtime by cutting the edges that intersect with a certain plane. It doesn't cut by a size or anything, nor does it go through all boundaries of an object.
> 
> I'm guessing you would need to iterate over the object's nodes and move the nodes along the intersecting edge in the opposite normal direction? (i.e. to reduce the boundary for 0.09 cm)
> 
> Hope this helps

Is it possible to do using meshcutter....can you help for me ...using any code
